export { default as GithubLogo } from "@/app/components/svgs/github.svg";
export { default as LinkedinLogo } from "@/app/components/svgs/linkedin.svg";
export { default as ArrowDown } from "@/app/components/svgs/arrowDown.svg";
export { default as CircularScrollTexts } from "@/app/components/svgs/circularScrollTexts.svg";
export { default as NoiseFilter } from "@/app/components/svgs/noiseFilter.svg";
export { default as Dev } from "@/app/components/svgs/dev.svg";
export { default as CircularMask } from "@/app/components/svgs/circularMask.svg";
export { default as CursorSVG } from "@/app/components/svgs/cursor.svg";
export { default as DiagonalArrow } from "@/app/components/svgs/diagonalArrow.svg";
